### ISSUE TITLE
Feature: PostGres

### ISSUE THREAD

**Issue by thebetterjort** [wrannaman/generators#6]
Any interest in adding PostGres support? Thinking of Postgres + Hasura.

**Comment by wrannaman** [comment]
Yeah that's a possibility. I was waiting for someone to ask for postgres or sql!

**Comment by wrannaman** [comment]
I have a hosted version https://noco.io/ that will support MySQL at the moment. I could also open it up for PostgreSQL though if you need to get super weird with it, it's not going to work well just yet!
