### ISSUE TITLE
Feature: MySQL/MariaDB support

### ISSUE THREAD

**Issue by boardfish** [wrannaman/generators#8]
Not much more to say, really.

**Comment by wrannaman** [comment]
noted, thanks @boardfish. Will add it as a feature request. MySQL will probably come first

**Comment by boardfish** [comment]
> For all practical purposes, MariaDB is a binary drop in replacement of the same MySQL version (for example MySQL 5.1 -> MariaDB 5.1, MariaDB 5.2 & MariaDB 5.3 are compatible. MySQL 5.5 is compatible with MariaDB 5.5 and also in practice with MariaDB 10.0 , MySQL 5.6 is compatible with MariaDB 10.0 and MySQL 5.7 is compatible with MariaDB 10.2 ).

From mariadb.com - they're effectively one and the same.

**Comment by wrannaman** [comment]
I'll probably use https://sequelize.org/ so Postgres, MySQL, MariaDB, SQLite and Microsoft SQL Server *should* work.

**Comment by wrannaman** [comment]
Check out https://noco.io/ It's a hosted version that will work with mysql
