### ISSUE TITLE
Feature: Generate a server from an OpenAPI spec

### ISSUE THREAD

**Issue by boardfish** [wrannaman/generators#9]
It'd be good if this project could work from an OpenAPI spec, similar to what openapi-generator does. I think that project is heading towards generating servers, but this one already has the grounding for it. Of course, this would open up a lot of issues beyond the usual CRUD operations. Perhaps in the instance of getting the DB ready, it might still need a JSON schema.

**Comment by wrannaman** [comment]
oh i see so input is an openAPI spec? That could be done. Right now the json maps nicely to a mongo schema but when I do mysql it's going to have to be more flexible and the OpenAPI spec as both input and output so to speak sounds correct
